Feature branch
Luckyaremu/enumerable pull request #2
Opened 2020-03-22 13:51 UTC by Luckyaremu

#Enumerables_method

1. Git-flow fixed
2. Linters error fixed

2020-03-22 17:46 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Luckyaremu :handshake: 

### Good job creating methods for all the enumerable now let's make them work like the real enumerable methods :construction: :construction_worker_man: 

## Project Specification (requirements from Odin)

* [ ] should have working `my_each`  identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_select` identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_any?`  identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
* [ ] should have working `multiply_els`  that uses `my_inject` as described on Odin ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/multiply_els.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))

- The main problem I see in your Enumerable methods not working properly is that you use 2 methods that aren't defined in your my_each and my_each_with_index Enumerable module, I have put comments in your code specifying which methods need to be defined

- Please use this [guide](
https://ruby-doc.org/core-2.6.5/Enumerable.html) to find how Ruby's Enumerable methods work and make sure all of your Enumerable methods have the same result as all of the examples given in the guide before your next submission.

## General

- [ ] Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- Add a couple of lines more to your pull request description explaining what you accomplished by making this project.

### That's it! :raised_hands: 

### Please :pray: work on this changes :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-03-22 17:46 UTC, euqueme commented on enumerable.rb
> +    return to_enumerable(:my_each) unless my_each_given?
- [ ] on line #6 you use my_each_given? method but this method is not defined in your Enumerable module, let's define it or use a different way to make this validation work

2020-03-22 17:46 UTC, euqueme commented on enumerable.rb
> +    return to_enumerable(:my_each_with_index) unless my_each_with_index_given?
- [ ] on line #17 you use my_each_with_index_given? method but this method is not defined in your Enumerable module, let's define it or use a different way to make this validation work

2020-03-23 10:32 UTC, Luckyaremu commented
#Enumerables method
1. my_each error fixed.
2. my_each_with_index error also fixed.
3. disable the allcaps documents to fix all other erros.

2020-03-23 18:11 UTC, kobiyoyo requested changes
## Hi @Luckyaremu    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
- [ ] Kindly refer to this doc for guidance https://ruby-doc.org/core-2.6.5/Enumerable.html 
- [ ] `my_each` 
-  returns an Enumerator if no block is given:
  `p [1, 2, 3].my_each` returns `#<Enumerator>`
- [ ] `my_each_with_index`  
- returns an Enumerator if no block is given:
  `p [1, 2, 3].my_each_with_index` returns `#<Enumerator>`
- it calls the given block once for each element in self
##### For example
      `my_each_output = ' ' `
      `my_each_output_two = ' ' `
      `block = proc { |y, x| my_each_output += "Hello: #{y}, in: #{x}\n" }`
      `block_two = proc { |y, x| my_each_output_two += "Hello: #{y}, in: #{x}\n" }`
      `[1,2,32,32,3,21,1,23,12].each_with_index(&block_two)`
      `[1,2,32,32,3,21,1,23,12].my_each_with_index(&block)`
       `p my_each_output ==  my_each_output_two ` this should return `true`

- [ ] `my_all`  
- returns true if the block never returns false or nil
  `  block =  proc { |num| num < 200 } `
    `  p [2,32,32].my_all?(&block)  `should return `true`
- when no block or argument is given returns true when none of the collection members are false or nil:
 `p [1, true, 'hi', []].my_all?` should return `true`.
- when a class is passed as an argument returns true if all of the collection is a member of such class
`p [1,1,1].my_all?(Integer)` should return `true`
-  when a Regex is passed as an argument returns true if all of the collection matches the Regex
`p ['d','d'].my_all?(/d/)` should return `true`
- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
`p [3,3,3,3].my_all?(3)` should return `true`


- [ ] `my_any?`:
- returns true if the block ever returns a value other than false or nil
`block = proc { |num| num <= 3 }`
`p [12,12,13,1,4].my_any?(&block)` should return `true`

- when no block or argument is given returns true if at least one of the collection is not false or nil
`p [nil, false, nil, false].my_any?` - should return `false`
- when a class is passed as an argument returns true if at least one of the collection is a member of such class
`p [12,3,34].my_any?(Integer)` should return `true`
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
`p ['ghetto','wild'].my_any?(/z/)` should return `false`
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
`p ['cat',2,32,].my_any?('cat')` should return `true`

- [ ] `my_none?`:
- returns true if the block never returns true for all elements
` block = proc { |num| num > 2 }`
` p [2,23,21,12].my_none?(&block)` should return `false`
- When no block or argument is given returns true only if none of the collection members is true
`p  [nil, false, true, []].my_none?`  should return `false`
- When a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
`p ['hello'].my_none?(5)` - should return `true`
- when a class is passed as an argument returns true if none of the collection is a member of such class
`p [3,3,3,3].my_none?(String)`  should return `true`
- when a Regex is passed as an argument returns true only if none of the collection matches the Regex
`p ['hello','milk','milo'].my_none?(/z/)` should return `true`



- [ ] `my_count`
-  returns the number of items in enum through enumeration
`p [8,87,6,5].my_count` should return `4`
- counts the number of items in enum that are equal to item if an argument is given:
`p  [1, 2, 3].,my_count(2)` should return `1`
-  my_count counts the number of elements yielding a true value if a block is given
`block = proc { |num| num < (2 + 24) / 2 }`
`p [23,13,12,43].my_count(&block)` should return 1
- [ ] `my_map` 
- returns an Enumerator if no block is given:
  `p [1, 2, 3].my_map` returns `#<Enumerator>`
- returns a new array with the results of running block once for every element in enum.
`block = proc { |num| num < (2 + 7) / 2 }`
`p [22,4,3,42,43].my_map(&block)` should return `[false, false, true, false, false]`
- [ ] `my_inject`:
- When a symbol is specified combines each element of the collection by applying the symbol as a named method
`p (5..10).my_inject(2, :*) - should return 302400`
- Combines all elements of enum by applying a binary operation, specified by a block:
 `p (1..5).my_inject(4) { |prod, n| prod * n }` should return 480


- [ ] `my_select`  
- returns an Enumerator if no block is given:
  `p [1, 2, 3].my_select` returns `#<Enumerator>`
- returns an array containing all elements of enum for which the given block returns a true value
block = proc { |num| num < 24 }
p [23,13,12,43].my_select(&block) should return [23, 13, 12]







### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-03-24 09:46 UTC, Luckyaremu commented
#1Enumerables.
1. worked on all the recommendations from my_each to my_inject
2. Checked and fix all linters errors
3. Disabled the my_inject errors

2020-03-24 18:56 UTC, euqueme requested changes
>### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @Luckyaremu  :handshake: 

### Thank you for doing most of the changes requested by me and the previous reviewer, your project is getting better and better every time, please address the changes I have left in your code :point_down: 

### That's it! :raised_hands: 

### Please :pray: do the changes :man_technologist:  and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-03-24 18:56 UTC, euqueme commented on enumerable.rb
> +  end
- [ ] When I try to test all of these enumerable methods: 

- my_all?
- my_any?
- my_none?
- my_count?

I'm getting an error similar to this:
```ruby
NoMethodError:
        undefined method `nill?'
```
I think it's a typo change 'nill' for 'nil' and make sure that you can run all of the examples in this guide: https://ruby-doc.org/core-2.6.5/Enumerable.html using your own Enumerable methods before your next submission, as it was requested in previous reviews.

2020-03-24 18:56 UTC, euqueme commented on enumerable.rb
> +  end
#### my_map

- [ ] given a block returns a new array with the results of running the block once for every element in enum.

```ruby
puts [18, 22, 5, 6] .my_map {|num| num < 10 }  => [false, false, true, true]
```
- Real map retrieves the right answer
![image](https://user-images.githubusercontent.com/52209067/77464866-6d6ffb00-6dcd-11ea-9cc1-fefe86bcf840.png)

- Your my_map retrieves a NameError
![image](https://user-images.githubusercontent.com/52209067/77464928-88db0600-6dcd-11ea-8e45-d2b0885ef12f.png)

- [ ] enumerables my_map accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum
Given:
```ruby
block = proc { |num| num < (2 + 7) / 2 }
```
The result should be
```ruby
puts  [22,4,3,42,43].my_map(&block) => [false, false, true, false, false]
```

- Real map retrieves the correct answer
![image](https://user-images.githubusercontent.com/52209067/77463288-fcc7df00-6dca-11ea-8c76-5770dbd5dee3.png)

- Your my_map is returning a NameError
![image](https://user-images.githubusercontent.com/52209067/77463326-10734580-6dcb-11ea-86ea-8614751d652f.png)

[OPTIONAL]

- [ ] In the specifications of the project in the [Odin project](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks) # 12, you were asked to modify your my_map method to take either a proc or a block. And if both a proc and a block are given, only execute the proc. The real map doesn't have this feature, but you were asked to have it so I strongly recommend working on it

Given 
```ruby
my_proc = Proc.new {|num| num > 10 }
```

Result should be
```ruby
puts [18, 22, 5, 6] .my_map(my_proc) {|num| num < 10 }  => [true, true, false, false]
```

2020-03-25 16:20 UTC, Luckyaremu commented
#enumerables
- my_all?, my_any?, my_none?, my_count? all errors fixed.
- all linters errors fixed and disabled order errors

2020-03-25 18:17 UTC, pelzolga123 commented
## Hi Lucky! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your did amazing work so far :+1: 
One more method is not working correctly, you need to fix that:
* [ ] `my all?` is giving two errors:
 ```ruby 
  NoMethodError:
        undefined method nill
 
```
```ruby 
  NoMethodError:
        undefined method self
 
```
* [ ] Linters config: Do not make any changes in config files - they represent style guidelines that you share with your team - which is a group of all Microverse students. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-03-25 18:18 UTC, pelzolga123 commented on enumerable.rb
>    end
Change `nill` to 'nil` and it will fix first NoMethodError.

2020-03-26 06:18 UTC, Luckyaremu commented
#enumerables
-typo error fixed

2020-03-26 19:08 UTC, bolah2009 requested changes
Hi @Luckyaremu 

Please let's remember that the objective is to create a method that is identical to the ruby enumerable methods but does not use such methods directly to create it.

   > ![Screenshot](https://user-images.githubusercontent.com/36057474/77683926-7dd4d100-6f99-11ea-9352-9ed27eafe15d.png)

Kindly write the methods without using the ruby's enumerable methods, see examples of how they work here => https://ruby-doc.org/core-2.6.5/Enumerable.html

Check out the comments below and remember to test your methods before submitting another CRR

You can set up a 1-on-1 with full-time TSEs if you need help via this link => https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-

#### :recycle:  Make these changes and submit another code review request. 👍🏾

#### Feel free to reach me on slack if you having issues implementing these features. :relaxed: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-03-26 19:08 UTC, bolah2009 commented on enumerable.rb
> +    each do |x|
Please let's not use `each` but create a custom one instead.

> Create #my_each, a method that is identical to #each but (obviously) does not use #each. You’ll need to remember the yield statement. Make sure it returns the same thing as #each as well.


![image](https://user-images.githubusercontent.com/36057474/77683926-7dd4d100-6f99-11ea-9352-9ed27eafe15d.png)

2020-03-26 19:08 UTC, bolah2009 commented on enumerable.rb
> +    each do |x|
Same here too

2020-03-26 19:08 UTC, bolah2009 commented on enumerable.rb
> +    return ar.self proc if proc
Could you verify that this line is functional, currently there's an error:

```
     NoMethodError:
       undefined method `self' for #<Array:0x0000560c349193d0>
```

Is there a reason to call the `self` method on the enumerable `self`?
This is equivalent to calling `self.self`. :thinking:

2020-03-26 19:08 UTC, bolah2009 commented on enumerable.rb
> +    return ar.any?(proc) if proc
You seem to be using ruby's `any?` instead of creating a custom one.

2020-03-26 19:08 UTC, bolah2009 commented on enumerable.rb
> +    return ar.none?(proc) if proc
You seem to be using ruby's `none?` instead of creating a custom one.

2020-03-26 19:08 UTC, bolah2009 commented on enumerable.rb
> +      ar.each do |x|
Please, let's use the custom method instead

2020-03-26 19:08 UTC, bolah2009 commented on enumerable.rb
> +    return cum += arr.reduce(reg) if reg.is_a?(Symbol) && cum.is_a?(Integer)
`reduce` is the same method as `inject`, instead of using the ruby's method kindly create a custom one.

2020-04-05 10:42 UTC, Luckyaremu commented
#enumerable
Recommendations from my_each to  my_none? fixed.
all linters errors treated.

2020-04-06 12:05 UTC, majovanilla requested changes
Hey @Luckyaremu , 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯

You are almost there!! I think you can make it so the next iteration your project is approved. Just don't break anything while fixing the next comments!! :sweat_smile: 

You have a similar problem with three of your methods, so once you figure out how to solve it with one, you just need to apply the same logic to all: 

my_all?, my_any?, my_none? Don't take into account:
- When you pass a class as an argument. `['this', 'is', 'a', 'string'].my_all?(String) => True` 
- When you pass a regex as an argument.  `[8, 7, 6, 5].my_all?(/d/) => True` 
When you pass a pattern as an argument.  `['this', 'is', 'a', 'string'].my_all?('this) => False` 

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes


Good Luck!! :stars:

2020-04-06 12:05 UTC, majovanilla commented on enumerable.rb
> +  end
Please check the specifics on this method in [here](https://ruby-doc.org/core-2.6.5/Enumerable.html): 
![Screenshot from 2020-04-06 06-52-26](https://user-images.githubusercontent.com/51926937/78555733-435a0800-77d3-11ea-89cf-ad533ad8dfed.png)

Right now, your code doesn't take these scenarios into account:
- If you pass a class as an argument (to check if all the elements are strings, for example) should return true or false.
-  If you pass a Regex as an argument  (to check if all the elements are digits, for example) should return true or false.
- If you pass another pattern as an argument  (to check if all the elements are 0, for example) should return true or false.

All the cases above are returning the array again, This shouldn't happen.

2020-04-06 12:05 UTC, majovanilla commented on enumerable.rb
> +  end
Check your my_any? method against the my_all? comments above, because it's happening the same thing with:

- Class as an argument
- Regex as an argument
- String as an argument

2020-04-06 12:05 UTC, majovanilla commented on enumerable.rb
> +  end
Check your my_none? method against the my_all? comments above, because it's happening the same thing with:

- Class as an argument
- Regex as an argument
- String as an argument

2020-04-06 19:35 UTC, Luckyaremu commented
#enumerable
Recommendations from my_all, my_none and my_any worked on.

Linters throwing error that looks like update on Linters itself, All requirement on Linters was properly done.

2020-04-06 23:15 UTC, majovanilla requested changes
Hi @Luckyaremu 

Nice work. Your are passing more tests!! Still, I noticed you didn't address some of the cases I pointed out in the previous review. Please check them and make the necessary changes!

Also, check the other comments I made below.

Check your interest, too. They are not passing.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-06 23:15 UTC, majovanilla commented on README.md
> +
Improve your Readme file. It should be descriptive of the project. You are using the correct template but now you need to fill it with information about your project. You can add details about what you did in this project, why you did it, how you did it...Check this [link](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more info.

2020-04-06 23:15 UTC, majovanilla commented on enumerable.rb
> +    return cum += arr.reduce(reg) if reg.is_a?(Symbol) && cum.is_a?(Integer)
> `reduce` is the same method as `inject`, instead of using the ruby's method kindly create a custom one.

Please address this issue.

2020-04-07 00:49 UTC, Luckyaremu commented
#enumerable
Recommendations on my_inject worked on.
Readme updated

Linters throwing error that looks like update on Linters itself, All requirement on Linters was properly done.

2020-04-07 03:10 UTC, majovanilla requested changes
Hey @Luckyaremu 

You are one step closer!!! You passed more tests this time. But still have some missing cases (some of them were already pointed out before, so please make sure you address everything before submitting a new code review)

Check the code below and make the changes please!

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +  end
Your method doesn't take into consideration the next options:
`[1,2,3,4,5].my_all?(Integer) => true`
`[1,2,3,4,5].my_all?(String) => false`

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +      my_each { |x| return false unless reg == x }
What is reg?? This is not working when you look for a regular expression like this:
`['first', 'focus', 'friend'].my_all?(/f/) => true`
`['first', 'focus', 'friend'].my_all?(/a/) => false`

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +  end
You have the same missing cases as the my_all? Please add them

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +      my_each { |x| res = true if yield(x) }
It should say the opposite. my_none should return false if one of the elements in the enumerable is true.

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +      my_each { |x| res = true if reg == x }
You are not defining `reg`

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +    res = false
This method is the opposite of my_all?

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +    end
You don't consider the case where no argument or block is given:
`[nil, nil, false, false].my_none? => true`
`[nil, nil, false, true].my_none? => false`
`ArgumentError:
       tried to create Proc object without a bloc
`

You don't consider the case when a Class is given as an argument:
`[1,2,3,4,5].my_none?(Integer) => false`
`[1,2,3,4,5].my_none?(String) => true`
`ArgumentError:
       tried to create Proc object without a bloc
`

You don't consider the case when a Regex is the argument:
`['first', 'focus', 'friend'].my_none?(/f/) => false`
`['first', 'focus', 'friend'].my_none?(/a/) => true`
`ArgumentError:
       tried to create Proc object without a bloc
`

You don't consider the case when an element is given as an argument:
`[1,2,3,4,5].my_none?(10) => true`
`[1,2,3,4,5].my_none?(2) => false`
`ArgumentError:
       tried to create Proc object without a bloc
`

2020-04-07 03:10 UTC, majovanilla commented on enumerable.rb
> +  end
You are not defining arr in this method.

2020-04-07 15:34 UTC, Luckyaremu commented
#enumerable
Recommendations on my_inject, my _all, my_none, and my_any worked.

Linters throwing error that looks like update on Linters itself, All requirement on Linters was properly done.

2020-04-07 19:21 UTC, mosesogwo requested changes
**Hi @Luckyaremu :clap:. It's been a long journey on this project but it's going to be worth it.**
- As we discussed, ensure you test your methods for the correct output before submitting for a re-review.

**More :muscle:**

### Status: Changes required.

2020-04-08 16:48 UTC, Luckyaremu commented
#enumerable
worked on my_inject, my _all, my_none, and my_any, and test all methods from my each to my inject with examples. All test methods attached to the test.txt file.

Linters throwing error that looks like update on Linters itself, All requirement on Linters was properly done.

2020-04-08 18:24 UTC, pelzolga123 approved these changes
Approved.

2020-04-08 18:24 UTC, pelzolga123 commented
## Hi Lucky,
### You did an amazing job! Congratulation :+1: Approved.
Go ahead and merge to dev-branch.
_Goodluck in your next project_ *Happy coding*

2020-04-08 19:29 UTC, merged