Feature
Luckyaremu/enumerable pull request #6
Opened 2020-04-09 09:59 UTC by Luckyaremu

#Enumerables methods

- Rspec testing methods done from my_each to my_multiply
-All linters requirements properly done
-The linter error showing is as a result of bug from linters

2020-04-09 13:44 UTC, euqueme commented
Hello @Luckyaremu I can't start the review because I don't see your coding partner commits or as a participant at all but the code review request was made as a team,

:pray: Please if both of you worked evenly in this project state it in your Pull Request description and add Kotoku Kennedy as a collaborator.

:pray: If you worked alone in this project please mark the checkbox that says you worked alone in this project when you submit for a code review again

PROJECT STATUS: INVALID :stop_sign:

2020-04-09 14:33 UTC, kotoku-code commented
RSPEC for enumerable project
- Used Rspec
- Fixed linter error
- Updated Readme

Thank you for reviewing our code, kindly let us know if there are any corrections needed to be made.

kind regards

2020-04-09 18:07 UTC, mosesogwo requested changes
**Hi @Luckyaremu, @kotoku-code:clap:. Good attempt on testing your methods. Let's make these improvements :fast_forward:**

- Add a space between describe blocks in your spec file.
- For **my_each, my_each_with_index and my_select** specs, add tests for the negative expectations. For example `expect([1, 2, 3, 4, 'hi'].my_each { |x| print x + 1 }).not_to eql([1, 2, 3, 4, 'hi'])`
- For **my_all?, my_any?, my_none?** methods, add tests for the cases where a Class and a Regex is provided as argument.
- Address the comments I made on the spec file
- A better title for your PR will be "RSpec Testing" 
- The test.txt file shouldn't be committed. Your spec file is the appropriate test file.

_**Kindly make these changes and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-04-09 18:07 UTC, mosesogwo commented on spec/enumerable_spec.rb
> +  end
When does it return false? Write a test for it.

2020-04-09 18:07 UTC, mosesogwo commented on spec/enumerable_spec.rb
> +  end
What does it return when only some of the elements return true? Write a test for it.
Also write a test for when all the elements return false for the block.

2020-04-09 18:07 UTC, mosesogwo commented on spec/enumerable_spec.rb
> +    it 'returns true if all the elements matches' do
It returns false (not true), if all the elements satisfy the block.

2020-04-09 18:07 UTC, mosesogwo commented on spec/enumerable_spec.rb
> +  end
When does my_none? return false. Add tests for it.

2020-04-09 18:07 UTC, mosesogwo commented on spec/enumerable_spec.rb
> +  end
Where is the test?

2020-04-09 18:07 UTC, mosesogwo commented on spec/enumerable_spec.rb
> +  end
Write test for when no block is given to my_map

2020-04-09 18:07 UTC, mosesogwo commented on spec/enumerable_spec.rb
> +    it 'returns a new array with the classes of each element of the array' do
my_inject **does not returns a new array with the classes of each element of the array**. Correct the test description.

Add tests for when a symbol is supplied and when an initial value is provided.

2020-04-09 19:36 UTC, Luckyaremu commented
#RSpec Testing

Rspec testing methods updated. More methods added for testing.

2020-04-09 23:15 UTC, Forison requested changes
## Staus:: Require changes🛑
# 🙋‍♂️
you have done a good job so far. here are a few areas your test has to cover.
Your tests must cover all the functionalities of each custom method. 
* [ ] ```my_each```, ```my_select```,``` my_each with```, ```my_map``` return enum when no block is given. let us test that functionality.
* [ ]  Some of the arrays used are repeated, let us refactor our tests to have those arrays to become global variables. use ```let(:array_name) { some array }```.
### Happy coding💻
Addo

2020-04-10 00:10 UTC, Luckyaremu commented
#RSpec Testing

Reviews treated

2020-04-10 00:30 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but you haven't implemented changes stipulated by the previous TSE. 
### General
- [ ] Let's implement those changes by previous TSE.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-10 14:24 UTC, Luckyaremu commented
#RSpec Testing

Rspec testing methods updated. More methods added for testing my_each, select, each_with_index.

2020-04-10 18:15 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Check comments below .


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-04-10 18:15 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +    end
You should have one `it` block for each expected behaviour

2020-04-10 18:15 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +    end
You should have one it block for each expected behaviour

2020-04-10 18:15 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +    end
You should have one it block for each expected behaviour

2020-04-10 18:15 UTC, kobiyoyo commented on spec/enumerable_spec.rb
> +    end
You should have one it block for each expected behaviour

2020-04-10 20:19 UTC, Luckyaremu commented
#RSpec Testing

Rspec testing methods updated. Methods fixed for testing my_each, my_map, select, each_with_index.

2020-04-11 17:02 UTC, maelfosso approved these changes
# Congratulations :clap: 

You can merge it :+1: 
Good luck with the next step :handshake: 

Mael FOSSO

2020-04-11 19:59 UTC, merged